name: dns_changer
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  google_nav_bar: ^5.0.6
  shared_preferences: ^2.3.2
  window_manager: ^0.4.2
  flutter_spinkit: ^5.2.1
  hive: ^2.2.3
  bitsdojo_window: ^0.1.6
  path_provider: ^2.1.4
  windows_single_instance: ^1.0.1
  tray_manager: ^0.2.3
  flutter_vpn: ^0.12.0
  file_picker: ^8.1.2
  process_run: ^1.1.0
  package_info_plus: ^8.0.2
  http: ^1.2.2
  url_launcher: ^6.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/tray.ico
